[build]
  image="grafana/grafana-enterprise:10.0.3-ubuntu"

[env]
  GF_USERS_DEFAULT_THEME="light"

[mounts]
  source="grafana_data"
  destination="/var/lib/grafana"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
